// <auto-generated />
using System;
using Gym.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gym.Models.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260428094551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Gym.Models.Entities.AimOfPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AimsOfPlan");
                });

            modelBuilder.Entity("Gym.Models.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Complex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMuscle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdMuscle");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Gym.Models.Entities.ExerciseInTraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdExercise")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTraining")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdExercise");

                    b.HasIndex("IdTraining");

                    b.ToTable("ExercisesInTraining");
                });

            modelBuilder.Entity("Gym.Models.Entities.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMuscleGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdMuscleGroup");

                    b.ToTable("Muscles");
                });

            modelBuilder.Entity("Gym.Models.Entities.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");
                });

            modelBuilder.Entity("Gym.Models.Entities.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdTrainingPlan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTrainingTypeSequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdTrainingPlan");

                    b.HasIndex("IdTrainingTypeSequence");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("Gym.Models.Entities.TrainingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdAimOfTraining")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTrainingType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainingFrequency")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdAimOfTraining");

                    b.HasIndex("IdTrainingType");

                    b.HasIndex("IdUser");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("Gym.Models.Entities.TrainingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrainingTypes");
                });

            modelBuilder.Entity("Gym.Models.Entities.TrainingTypeSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMuscleGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTrainingType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderInCycle")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdMuscleGroup");

                    b.HasIndex("IdTrainingType");

                    b.ToTable("TrainingTypeSequences");
                });

            modelBuilder.Entity("Gym.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gym.Models.Entities.Exercise", b =>
                {
                    b.HasOne("Gym.Models.Entities.Muscle", "Muscle")
                        .WithMany("Exercises")
                        .HasForeignKey("IdMuscle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("Gym.Models.Entities.ExerciseInTraining", b =>
                {
                    b.HasOne("Gym.Models.Entities.Exercise", "Exercise")
                        .WithMany("ExercisesInTraining")
                        .HasForeignKey("IdExercise")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym.Models.Entities.Training", "Training")
                        .WithMany("ExercisesInTraining")
                        .HasForeignKey("IdTraining")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("Gym.Models.Entities.Muscle", b =>
                {
                    b.HasOne("Gym.Models.Entities.MuscleGroup", "MuscleGroup")
                        .WithMany("Muscles")
                        .HasForeignKey("IdMuscleGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("Gym.Models.Entities.Training", b =>
                {
                    b.HasOne("Gym.Models.Entities.TrainingPlan", "TrainingPlan")
                        .WithMany("Trainings")
                        .HasForeignKey("IdTrainingPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym.Models.Entities.TrainingTypeSequence", "TrainingTypeSequence")
                        .WithMany("Trainings")
                        .HasForeignKey("IdTrainingTypeSequence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");

                    b.Navigation("TrainingTypeSequence");
                });

            modelBuilder.Entity("Gym.Models.Entities.TrainingPlan", b =>
                {
                    b.HasOne("Gym.Models.Entities.AimOfPlan", "AimOfTraining")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("IdAimOfTraining")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym.Models.Entities.TrainingType", "TrainingType")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("IdTrainingType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym.Models.Entities.User", "User")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AimOfTraining");

                    b.Navigation("TrainingType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gym.Models.Entities.TrainingTypeSequence", b =>
                {
                    b.HasOne("Gym.Models.Entities.MuscleGroup", "MuscleGroup")
                        .WithMany("TrainingTypeSequences")
                        .HasForeignKey("IdMuscleGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym.Models.Entities.TrainingType", "TrainingType")
                        .WithMany("TrainingTypeSequences")
                        .HasForeignKey("IdTrainingType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuscleGroup");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("Gym.Models.Entities.AimOfPlan", b =>
                {
                    b.Navigation("TrainingPlans");
                });

            modelBuilder.Entity("Gym.Models.Entities.Exercise", b =>
                {
                    b.Navigation("ExercisesInTraining");
                });

            modelBuilder.Entity("Gym.Models.Entities.Muscle", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Gym.Models.Entities.MuscleGroup", b =>
                {
                    b.Navigation("Muscles");

                    b.Navigation("TrainingTypeSequences");
                });

            modelBuilder.Entity("Gym.Models.Entities.Training", b =>
                {
                    b.Navigation("ExercisesInTraining");
                });

            modelBuilder.Entity("Gym.Models.Entities.TrainingPlan", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("Gym.Models.Entities.TrainingType", b =>
                {
                    b.Navigation("TrainingPlans");

                    b.Navigation("TrainingTypeSequences");
                });

            modelBuilder.Entity("Gym.Models.Entities.TrainingTypeSequence", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("Gym.Models.Entities.User", b =>
                {
                    b.Navigation("TrainingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
